spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.111.166:3306/StrongestScholar?useSSL=false&useUnicode=true&characterEncoding=utf-8
    password: ENC(HavpzcukB4Dh29SCVW11NvTentUjg/6WTtqZsp8aTr0=)
    username: strongestscholar
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /**

jasypt:
  encryptor:
    password: Wae$avVyj5JTfy2AWean+23RAW=

server:
  servlet:
    context-path: /strongestscholar
  port: 8089

mp:
  appid: wxcb5091163924072e
  appSecret: f9fb05b14ef2a8ac474d7b3c6778f8e9
  mch_id: 1493812802
  key: 14F72CD2E7F194109A8EBDB2A2EA52A9
  signType: MD5
  tradeType: JSAPI
  codeToOpenidUrl: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
  unifiedOrderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  notifyUrl: http://strongestscholar.dxtwangxiao.com/strongestscholar/api/v1/wechat/notify
  # 私有题库扫码登录
  questionForLibAppid: wxb2443bb573c6db02
  questionForLibAppSecret: af30d61327ccc136851d72beac26c9e4
  # 后台管理扫码登录
  backendAppid: wxb96bf7c22dd81558
  backendAppSecret: fbcf5dd0fdd970434b1b676dab47a45f
  # 微信开放平台接口
  authorizationUrl: https://open.weixin.qq.com/connect/qrconnect?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=snsapi_login&state=STATE#wechat_redirect
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
  transfersUrl: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
  certLocation: src/main/resources/certificate/apiclient_cert.p12

jwt:
  authOpen: false

